## Numpy数组的创建

### 从列表开始创建

In [2]:
import numpy as np

x = np.array([1,2,3,4,5])
print(x)
print(type(x))
print(type(x[0]))
print(x.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
(5,)


设置数组的数据类型

In [3]:
x = np.array([1,2,3,4,5], dtype='float32')
print(x)
print(type(x[0]))

[1. 2. 3. 4. 5.]
<class 'numpy.float32'>


#### 二维数组

In [5]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,13]])

print(x)
print(x.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 13]]
(4, 3)


### 从头创建数组

#### 创建长度为5的数组，值都为0

In [6]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

#### 创建一个2\*4的浮点型数组，值都为1

In [7]:
np.ones((2,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 创建一个3*5数组，值都为8.8

In [8]:
np.full((3,5), 8.8)

array([[8.8, 8.8, 8.8, 8.8, 8.8],
       [8.8, 8.8, 8.8, 8.8, 8.8],
       [8.8, 8.8, 8.8, 8.8, 8.8]])

#### 创建3*3的单位矩阵

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 创建一个线性序列数组，从1开始，到15结束，步长为2

In [10]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

#### 创建一个4个元素的数组，这四个数均匀分配到0~1

In [11]:
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

#### 创建一个10元素的数组，形成1~10^9的等比数列

In [18]:
np.logspace(0,9,10)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09])

#### np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0):
            
    start：代表序列的起始值。
    stop：代表序列的终止值。
    num：生成的序列数个数。
    endpoint：布尔类型值，默认是true。如果为true, 'stop'是最后一个样本；否则，它不包括在内。
    base：代表序列空间的底数，默认基底为10。
    dtype：代表序列数组项的数据类型。

In [21]:
np.logspace(1,9,6,base=3)
# 3^1 ~ 3^9 6个数的等比数列

array([3.00000000e+00, 1.73986384e+01, 1.00904206e+02, 5.85198599e+02,
       3.39388627e+03, 1.96830000e+04])

#### 创建一个在0~1之间均匀分布的随机数构成的数组

In [22]:
np.random.random((3,4))

array([[0.68070529, 0.86629335, 0.56719954, 0.28270892],
       [0.00498064, 0.92472319, 0.93388505, 0.38362164],
       [0.26320921, 0.01036221, 0.02428903, 0.59789368]])

#### 创建一个均值为0，标准差为1的正态分布的随机数构成的数组

In [28]:
np.random.normal(0,1,(10,))

array([-4.67435347e-01,  5.75817385e-03, -2.87145309e-01,  9.60928320e-01,
        3.59341877e-01, -1.79695529e-02, -1.03940841e+00,  6.81753575e-01,
        7.83003802e-01,  8.36809617e-04])

#### 创建随机整数

In [29]:
np.random.randint(0,10,(3,3))

array([[3, 5, 6],
       [7, 8, 0],
       [0, 8, 0]])

#### 随机重排列

In [32]:
x = np.array([10, 20, 30, 40])
y = np.random.permutation(x)  # 产生新数组
print(x,y)
np.random.shuffle(x)
print(x)  # 改变原数组

[10 20 30 40] [10 40 20 30]
[30 40 20 10]


#### 随机采样

按指定形状采样

In [33]:
x = np.arange(10, 25, dtype = float)
x

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24.])

In [34]:
np.random.choice(x, size=(4,3))

array([[24., 20., 14.],
       [11., 11., 24.],
       [21., 13., 21.],
       [15., 11., 21.]])

按概率采样

In [35]:
np.random.choice(x, size=(4,3), p=x/np.sum(x))

array([[19., 21., 22.],
       [17., 10., 20.],
       [11., 16., 24.],
       [19., 14., 19.]])

## 11.3 Numpy数组的性质

### 数组的属性

#### 数组的形状  shape

In [38]:
x.shape

(15,)

#### 数组的维度 ndim

In [39]:
x.ndim

1

#### 数组的大小 size

In [40]:
x.size

15

#### 数据类型  dtype

In [41]:
x.dtype

dtype('float64')

### 数组索引

#### 一维数组索引

In [42]:
x1 = np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x1[0]

0

In [45]:
x1[-1]

9

#### 多维数组的索引，以二维数组为例

In [46]:
x2 = np.random.randint(0, 20, (2,3))
x2

array([[17, 17,  3],
       [12,  8, 17]])

In [47]:
x2[0,0]

17

In [48]:
x2[0][0]

17

注意：numpy数组类型是固定的，向一个整数数组插入一个浮点值，浮点值回向下进行取整

In [49]:
x2[1,2] = 1.34
x2

array([[17, 17,  3],
       [12,  8,  1]])

### 数组的切片

#### 一维数组

In [51]:
x1 = np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
x1[:3]

array([0, 1, 2])

In [53]:
x1[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [65]:
x1[3::-1]  # 开始：结束：间隔(-1为倒叙，则前面的开始和结束也要倒过来)

array([3, 2, 1, 0])

#### 多维数组

In [55]:
x2 = np.random.randint(20,size=(3,4))
x2

array([[ 3, 16, 19,  6],
       [ 4, 15, 14, 14],
       [ 5,  6,  7, 14]])

In [66]:
x2[1::-1, 2::-1]

array([[14, 15,  4],
       [19, 16,  3]])

In [67]:
x2[2:0:-1, 3:0:-1]

array([[14,  7,  6],
       [14, 14, 15]])

#### 获取数组行与列

In [68]:
x3 = np.random.randint(20, size=(3,4))
x3

array([[11,  8, 16, 15],
       [19, 12,  9,  1],
       [ 4, 17,  3, 15]])

In [69]:
x3[1,:] # 第一行 所有列
x3[1]  # 简写

array([19, 12,  9,  1])

In [71]:
x3[:, 2]  # 第二列 所有行

array([16,  9,  3])

#### 注意： 切片是数组的视图，如果对切片的某个元素进行修改，则原数组对应元素也会发生改变

In [78]:
x4 = x3[:, 1]
x4[1] = 1
x3

array([[11,  8, 16, 15],
       [19,  1,  9,  1],
       [ 4, 17,  3, 15]])

#### 修改切片的安全方式  copy

In [81]:
x4 = x3[:, 1].copy()
x4[1] = 5
x3

array([[11,  8, 16, 15],
       [19,  1,  9,  1],
       [ 4, 17,  3, 15]])

### 数组的变形

In [83]:
x5 = np.random.randint(0,10,(12,))
x5

array([7, 5, 7, 7, 9, 1, 7, 6, 7, 0, 0, 8])

In [84]:
x5.shape

(12,)

In [85]:
x6 = x5.reshape(3,4)
x6

array([[7, 5, 7, 7],
       [9, 1, 7, 6],
       [7, 0, 0, 8]])

#### 注意： reshape 返回的 是 视图，而非副本

In [87]:
x6 = x5.reshape(3,4).copy()  # 同样可以转为副本
x6

array([[7, 5, 7, 7],
       [9, 1, 7, 6],
       [7, 0, 0, 8]])

#### 一维数组转行向量

In [89]:
x7 = x5.reshape(1,x5.shape[0])
x7

array([[7, 5, 7, 7, 9, 1, 7, 6, 7, 0, 0, 8]])

In [90]:
x7 = x5[np.newaxis, :]
x7

array([[7, 5, 7, 7, 9, 1, 7, 6, 7, 0, 0, 8]])

#### 一维数组转列向量

In [91]:
x8 = x5.reshape(x5.shape[0],1)
x8

array([[7],
       [5],
       [7],
       [7],
       [9],
       [1],
       [7],
       [6],
       [7],
       [0],
       [0],
       [8]])

In [93]:
x8 = x5[:,np.newaxis]
x8

array([[7],
       [5],
       [7],
       [7],
       [9],
       [1],
       [7],
       [6],
       [7],
       [0],
       [0],
       [8]])

#### 多维转一维

In [94]:
x6 = np.random.randint(0,10,(3,4))
x6

array([[0, 9, 0, 5],
       [0, 0, 5, 0],
       [2, 6, 2, 2]])

In [95]:
x9 = x6.flatten()
x9

array([0, 9, 0, 5, 0, 0, 5, 0, 2, 6, 2, 2])

flatten  返回的是副本

In [96]:
x10 = x6.ravel()
x10

array([0, 9, 0, 5, 0, 0, 5, 0, 2, 6, 2, 2])

ravel 返回视图

In [97]:
x11 = x6.reshape(-1)
x11

array([0, 9, 0, 5, 0, 0, 5, 0, 2, 6, 2, 2])

### 数组的拼接

In [99]:
x1 = np.array([[1,2,3],
              [4,5,6]])
x2 = np.array([[7,8,9],
              [0,1,2]])

#### 水平拼接 —— 非视图

In [100]:
x3 = np.hstack([x1,x2])
x3

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 1, 2]])

In [101]:
x3[0,0] = 0
x1

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
x4 = np.c_[x1,x2]
x4

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 1, 2]])

#### 直拼接 —— 非视图

In [105]:
x5 = np.vstack([x1, x2])
x5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

In [106]:
x6 = np.r_[x1, x2]
x6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 1, 2]])

### 数组的分裂

#### split 的用法

In [111]:
x6 = np.arange(9,0,-1)
x6

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [112]:
x1, x2, x3 = np.split(x6, [2, 7])
print(x1,x2,x3)

[9 8] [7 6 5 4 3] [2 1]


#### hsplit 的用法

In [113]:
x7 = np.arange(1, 26).reshape(5, 5)
x7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [116]:
left, mid, right = np.hsplit(x7, [2,4])
print(left,'\n\n',mid,'\n\n',right)

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]] 

 [[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]] 

 [[ 5]
 [10]
 [15]
 [20]
 [25]]


#### vsplit 的方法

In [117]:
upper,middle,lower = np.vsplit(x7,[1,3])
print(upper,'\n\n',middle,'\n\n',lower)

[[1 2 3 4 5]] 

 [[ 6  7  8  9 10]
 [11 12 13 14 15]] 

 [[16 17 18 19 20]
 [21 22 23 24 25]]


## Numpy 四大运算

### 向量化运算

#### 与数组的加减乘除

In [118]:
x1 = np.arange(1,6)
x1 

array([1, 2, 3, 4, 5])

In [119]:
print("x1+5",x1+5)
print("x1-5",x1-5)
print("x1*5",x1*5)
print("x1/5",x1/5)
print("-x1",-x1)
print("x1**2",x1**2)
print("x1//2",x1//2)
print("x1%2",x1%2)

x1+5 [ 6  7  8  9 10]
x1-5 [-4 -3 -2 -1  0]
x1*5 [ 5 10 15 20 25]
x1/5 [0.2 0.4 0.6 0.8 1. ]
-x1 [-1 -2 -3 -4 -5]
x1**2 [ 1  4  9 16 25]
x1//2 [0 1 1 2 2]
x1%2 [1 0 1 0 1]


#### 绝对值

In [120]:
x2 = np.array([1,-1,2,-2,0])
abs(x2)

array([1, 1, 2, 2, 0])

In [121]:
np.abs(x2)

array([1, 1, 2, 2, 0])

#### 三角函数

In [123]:
theta = np.linspace(0,np.pi,3)

In [124]:
print("sin(theta)", np.sin(theta))
print("con(theta)", np.cos(theta))
print("tan(theta)", np.tan(theta))

sin(theta) [0.0000000e+00 1.0000000e+00 1.2246468e-16]
con(theta) [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [126]:
x = [1, 0, -1]
print("arcsin(x)",np.arcsin(x))
print("arccos(x)",np.arccos(x))
print("arctan(x)",np.arctan(x))

arcsin(x) [ 1.57079633  0.         -1.57079633]
arccos(x) [0.         1.57079633 3.14159265]
arctan(x) [ 0.78539816  0.         -0.78539816]


#### 指数函数

In [128]:
x = np.arange(3)
x

array([0, 1, 2])

In [129]:
np.exp(x)

array([1.        , 2.71828183, 7.3890561 ])

#### 对数运算

In [131]:
x = np.array([1,2,4,8,10])
print("ln(x)", np.log(x))
print("log2(x)", np.log2(x))
print("log10(x)", np.log10(x))

ln(x) [0.         0.69314718 1.38629436 2.07944154 2.30258509]
log2(x) [0.         1.         2.         3.         3.32192809]
log10(x) [0.         0.30103    0.60205999 0.90308999 1.        ]


#### 两个数组运算

In [133]:
x1 = np.arange(1,6)
x1

array([1, 2, 3, 4, 5])

In [134]:
x2 = np.arange(6,11)
x2

array([ 6,  7,  8,  9, 10])

In [135]:
print("x1+x2", x1+x2)
print("x1-x2", x1-x2)
print("x1*x2", x1*x2)
print("x1/x2", x1/x2)
print("x1//x2", x1//x2)
print("x1%x2", x1%x2)

x1+x2 [ 7  9 11 13 15]
x1-x2 [-5 -5 -5 -5 -5]
x1*x2 [ 6 14 24 36 50]
x1/x2 [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
x1//x2 [0 0 0 0 0]
x1%x2 [1 2 3 4 5]


### 矩阵运算

In [136]:
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

#### 矩阵转置

In [137]:
y = x.T
y

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### 矩阵乘法

In [138]:
x.dot(y)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [140]:
np.dot(x,y)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

### 广播运算

    规则：
    如果两个数组形状不匹配，则数组会沿着维度为1（且仅为1）的维度进行扩展，来匹配另外一个数组，如果两个数组扩展后依然无法匹配则无法进行运算

In [141]:
x1 = np.ones((3,3))
x1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [142]:
x2 = np.arange(3)
x2

array([0, 1, 2])

In [144]:
x1+x2

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [148]:
x3 = np.arange(4).reshape(4,1)
x3

array([[0],
       [1],
       [2],
       [3]])

In [149]:
x2*x3

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

### 比较运算与掩码

#### 比较运算

In [150]:
x1 = np.random.randint(0,100,(10,10))
x1

array([[26, 39, 29, 89, 77, 15, 38, 72, 48, 98],
       [65, 70, 44, 98, 51, 26, 59, 79, 61, 63],
       [41, 28, 51, 59, 45, 26, 80, 15, 33, 86],
       [75,  5, 89, 83,  1, 59, 84, 16, 50, 71],
       [31, 32, 58, 10, 80, 11, 51, 68,  3, 38],
       [38, 70, 59, 73, 99, 62, 37, 50, 19, 20],
       [18, 19,  5, 35, 75, 20, 75, 63, 59, 71],
       [19, 37, 36,  7, 53, 13, 21, 10,  9, 16],
       [20, 81, 39, 47, 72, 13, 77, 91, 43, 67],
       [13, 92, 59,  0, 23, 87, 63,  8, 98, 49]])

In [151]:
x1 > 50

array([[False, False, False,  True,  True, False, False,  True, False,
         True],
       [ True,  True, False,  True,  True, False,  True,  True,  True,
         True],
       [False, False,  True,  True, False, False,  True, False, False,
         True],
       [ True, False,  True,  True, False,  True,  True, False, False,
         True],
       [False, False,  True, False,  True, False,  True,  True, False,
        False],
       [False,  True,  True,  True,  True,  True, False, False, False,
        False],
       [False, False, False, False,  True, False,  True,  True,  True,
         True],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False,  True, False, False,  True, False,  True,  True, False,
         True],
       [False,  True,  True, False, False,  True,  True, False,  True,
        False]])

In [153]:
np.all(x1 >= 0)

True

In [154]:
np.any(x1 < 0)

False

In [156]:
np.any(x1 == 0, axis=1)

array([False, False, False, False, False, False, False, False, False,
        True])

In [157]:
np.sum((x1 < 90) & (x1 > 50))

41

#### 将布尔数组作为掩码

In [159]:
x1[x1>50]

array([89, 77, 72, 98, 65, 70, 98, 51, 59, 79, 61, 63, 51, 59, 80, 86, 75,
       89, 83, 59, 84, 71, 58, 80, 51, 68, 70, 59, 73, 99, 62, 75, 75, 63,
       59, 71, 53, 81, 72, 77, 91, 67, 92, 59, 87, 63, 98])

### 索引

#### 一维数组

In [160]:
x = np.random.randint(100,size=10)
x

array([15, 19, 72, 10, 74, 33, 89, 37, 29, 39])

In [161]:
ind = [2, 6, 9]
x[ind]

array([72, 89, 39])

#### 结果形状与索引数组ind一致

In [162]:
ind = np.array([[1,0],
               [2,3]])
x[ind]

array([[19, 15],
       [72, 10]])